version: '3'

services:

  db1:
    image: cockroachdb/cockroach:v19.1.5
    container_name: db1
    ports:
      - 8081:8080
      - 26251:26257
    volumes:
      - ${PWD}/data/db1:/cockroach/cockroach-data"
    networks:
      - bluesteel-net
    command: start --insecure --advertise-addr=db1

  db2:
    image: cockroachdb/cockroach:v19.1.5
    container_name: db2
    ports:
      - 8082:8080
      - 26252:26257
    volumes:
      - ${PWD}/data/db2:/cockroach/cockroach-data"
    networks:
      - bluesteel-net
    command: start --insecure --advertise-addr=db2 --join=db1
    depends_on: 
      - db1

  db3:
    image: cockroachdb/cockroach:v19.1.5
    container_name: db3
    ports:
      - 8083:8080
      - 26253:26257
    volumes:
      - ${PWD}/data/db3:/cockroach/cockroach-data"
    networks:
      - bluesteel-net
    command: start --insecure --advertise-addr=db3 --join=db1
    depends_on: 
      - db1

  nats:
    image: nats:2.1.0
    container_name: messaging
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - bluesteel-net

  nats-relay:
    image: bluesteelabm/nats-relayd:${RELAYD_VERSION}
    ports:
      - 4223:4223
    networks:
      - bluesteel-net

networks:
  bluesteel-net:
